### ISSUE TITLE
Excessive background ram use.

### ISSUE THREAD

**Issue by roy13** [mendhak/gpslogger#585] opened 2017-08-24 01:57 UTC
As is this app is fantastic in automations for use with my home assistant. 
However I'm concerned with it's large ram usage in the background. It inevitably effects multitasking abilities.
In general it consumes 80-120mb.

**Comment by mendhak** [comment] 2017-08-27 09:14
So I've been trying for a few days to reproduce this on a few phones.  In the phone settings under app I can see that GPSLogger is going till 60-80 MB sometimes.  Assuming a memory leak I left it running for overnight and then checked the memory usage, however in memory analysis in IDEA I see it always hovering near 16MB. 

![image](https://user-images.githubusercontent.com/746276/29748529-692509f2-8b10-11e7-8a03-3483a3333601.png)

Main reason for looking there is to get an idea of what's resident in memory.  Are you seeing a constant high usage, or is it the average memory usage reported by the OS?  What are you using to track it

**Comment by roy13** [comment] 2017-08-28 00:29
![capture _2017-08-27-19-41-07 1](https://user-images.githubusercontent.com/13426512/29755418-019bd2fe-8bdb-11e7-97f3-d895c285f598.png)
![capture _2017-08-24-11-52-49 1](https://user-images.githubusercontent.com/13426512/29755427-0d8a6044-8bdb-11e7-91dc-aadf709eb78a.png)
From developers options from within the OS then running services.
Even if the app has not been brought to the foreground for several hours. 
Tested on android 6.0 & 5.1

**Comment by mendhak** [comment] 2017-08-28 11:06
Looks like what the OS reports is based on heap size whereas the Android Studio/IntelliJ figures are specific to the application.   I did a heap dump and got this


    Applications Memory Usage (in Kilobytes):
    Uptime: 129989875 Realtime: 259579076
    
    ** MEMINFO in pid 4185 [com.mendhak.gpslogger] **
                       Pss  Private  Private  SwapPss     Heap     Heap     Heap
                     Total    Dirty    Clean    Dirty     Size    Alloc     Free
                    ------   ------   ------   ------   ------   ------   ------
      Native Heap    14447    14364        0        0    32768    16522    16245
      Dalvik Heap    11705    11624        0        0    16160     7968     8192
     Dalvik Other     1753     1752        0        0                           
            Stack      540      540        0        0                           
           Ashmem        2        0        0        0                           
          Gfx dev     7014     6128        0        0                           
        Other dev        4        0        4        0                           
         .so mmap      988      196       52        0                           
        .jar mmap        0        0        0        0                           
        .apk mmap      544        0      420        0                           
        .ttf mmap       13        0        0        0                           
        .dex mmap     2977        8     2968        0                           
        .oat mmap     2302        0      200        0                           
        .art mmap     3270     2596      284        0                           
       Other mmap       29        4        0        0                           
       EGL mtrack      336      336        0        0                           
        GL mtrack    10524    10524        0        0                           
          Unknown      910      908        0        0                           
            TOTAL    57358    48980     3928        0    48928    24490    24437
     
     App Summary
                           Pss(KB)
                            ------
               Java Heap:    14504
             Native Heap:    14364
                    Code:     3844
                   Stack:      540
                Graphics:    16988
           Private Other:     2668
                  System:     4450
     
                   TOTAL:    57358       TOTAL SWAP PSS:        0
     
     Objects
                   Views:      262         ViewRootImpl:        1
             AppContexts:        5           Activities:        2
                  Assets:        4        AssetManagers:        2
           Local Binders:       21        Proxy Binders:       28
           Parcel memory:        9         Parcel count:       53
        Death Recipients:        1      OpenSSL Sockets:        3
                WebViews:        0
     
     SQL
             MEMORY_USED:      156
      PAGECACHE_OVERFLOW:       38          MALLOC_SIZE:       62
     
     DATABASES
          pgsz     dbsz   Lookaside(b)          cache  Dbname
             4       28            109    1499/241/14  /data/user/0/com.mendhak.gpslogger/databases/db_default_job_manager
     
     Asset Allocations
        zip:/data/app/com.mendhak.gpslogger-1/base.apk:/assets/fonts/materialdrawerfont.ttf: 5K

Of course the documentation is a bit out of date, so it isn't covering some of the bigger memory eaters listed, think I'm going to have to guess my way around this. I'll try to figure out if activity references aren't being released.

**Comment by danielfaust** [comment] 2017-08-28 11:48
There's https://github.com/square/leakcanary if it helps.

**Comment by mendhak** [comment] 2017-08-28 12:04
Oh very nice I will try this!

**Comment by mendhak** [comment] 2017-08-30 20:12
Alas nothing came from leakcanary. :disappointed:  I believe it's because leakcanary is looking directly at the app itself but the heap isn't being reported on which the OS does report on.  Not entirely sure  but I believe it's the activities themselves (the fragments and actionbar) which are contributing to the heap size. 

So I've started a [branch](https://github.com/mendhak/gpslogger/tree/memusage) - one of the main [commits](https://github.com/mendhak/gpslogger/commit/42dc337183a6bb234f2ef7506d98fbe2c64caa16) I've tried to unload stuff when back button is pressed.  I did notice a change, it was down to 44MB when pushed into background.  Not amazing but an improvement, albeit a minor one...

In case you want to test:
[APK](https://drive.google.com/open?id=0B6IOK82n4BkAWHEtYWd6MXlVT1U), [Signature](https://drive.google.com/open?id=0B6IOK82n4BkATWUxSHV1WjRoM2M), [Checksum](https://drive.google.com/open?id=0B6IOK82n4BkAYmU3c1dUN1piVlU)

**Comment by mendhak** [comment] 2017-12-19 21:58
Found an additional bit of code tweaking where I was using Event Bus `postSticky` - in turn this was causing a few items to stay in memory and invoking some events multiple times.  Minor impact but still worth mentioning.

**Comment by mendhak** [comment] 2018-01-11 22:38
v91 is released to market.  Now, have another go at watching its usage.  I'll close this thread for now.  If it comes back we should reopen this thread - easier to keep track of what has been attempted including the canary and heaping

**Closed by mendhak** 2018-01-11 22:38 UTC
