### ISSUE TITLE
Problem after the newest upgrade 8th February

### ISSUE THREAD

**Issue by 03397** [mendhak/gpslogger#801] opened 2020-02-10 17:35 UTC
Guys, after the  recent upgrade two days ago my device, after leaving the gps logger running  in the background, is misbehaving erratically mostly hanging and unresponsive.

In addition to that, I had enabled the do not log when I am not moving but now every time It gets get my location I get new pinpoint no matter what.
I have a Google Pixel 3 with Android 10.

**Comment by ChromoX** [comment] 2020-02-10 18:12
I'm having the same issues.

**Comment by mendhak** [comment] 2020-02-10 18:26
I just tried to deactivate v104 from the Play Store and I'm not allowed to, due to the SDK restrictions. 

Can you gather some debug logs and send it to me.  

I tested on several devices without problem so I'm going to have to guess at some features to remove for now.

**Comment by mendhak** [comment] 2020-02-10 18:49
Gather logs:  https://gpslogger.app/#troubleshooting


In the meantime I do think this may be activity recognition related.  If you disable the activity recognition feature "Don't log if I'm not moving" does the problem go away?

**Comment by ChromoX** [comment] 2020-02-10 20:17
I have the same hardware and software as @03397. The issue seems to affect the System UI, which then stops the phone from waking up properly because it seems SystemUI is being put in a hung situation which then causes GPSLogger to be killed given the following:

`15:09:12 WARN  GpsLoggingService.onDestroy:144 - GpsLoggingService is being destroyed by Android OS.`

I don't have the feature "Don't log if I'm not moving" on.

```
15:08:50 DEBUG CustomUrlJob.onRun:82 - HTTP request complete with successful response code Response{protocol=h2, code=200, message=, url=https://<my server>}
15:08:50 DEBUG AppSettings$1.d:92 - safeRunResult for com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@450d30c : true. re run:false. cancelled: false
15:08:50 DEBUG AppSettings$1.d:92 - [queue_RUN_JOB_RESULT_6] post message com.birbit.android.jobqueue.messaging.message.RunJobResultMessage@c748e94
15:08:50 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364062228621791
15:08:50 DEBUG AppSettings$1.d:92 - [priority_mq] looking for next message at time 1581364062228890228
15:08:50 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364062228890228
15:08:50 DEBUG AppSettings$1.d:92 - [consumer_4] remove message null
15:08:50 DEBUG AppSettings$1.d:92 - [priority_mq] next delayed job null
15:08:50 DEBUG AppSettings$1.d:92 - [queue_RUN_JOB_RESULT_6] remove message com.birbit.android.jobqueue.messaging.message.RunJobResultMessage@c748e94
15:08:50 DEBUG AppSettings$1.d:92 - consumer manager on idle
15:08:50 DEBUG AppSettings$1.d:92 - [priority_mq] consuming message of type RUN_JOB_RESULT
15:08:50 DEBUG AppSettings$1.d:92 - [queue_JOB_CONSUMER_IDLE_5] post message com.birbit.android.jobqueue.messaging.message.JobConsumerIdleMessage@64b3d1b
15:08:50 DEBUG AppSettings$1.d:92 - [consumer_4] will wait on the lock forever
15:08:50 DEBUG AppSettings$1.d:92 - [priority_mq] looking for next message at time 1581364062248485439
15:08:50 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364062248485439
15:08:50 DEBUG AppSettings$1.d:92 - [priority_mq] next delayed job null
15:08:50 DEBUG AppSettings$1.d:92 - [queue_RUN_JOB_RESULT_6] remove message null
15:08:50 DEBUG AppSettings$1.d:92 - [queue_CONSTRAINT_CHANGE_2] remove message null
15:08:50 DEBUG AppSettings$1.d:92 - [queue_ADD_JOB_3] remove message null
15:08:50 DEBUG AppSettings$1.d:92 - [queue_JOB_CONSUMER_IDLE_5] remove message com.birbit.android.jobqueue.messaging.message.JobConsumerIdleMessage@64b3d1b
15:08:50 DEBUG AppSettings$1.d:92 - [priority_mq] consuming message of type JOB_CONSUMER_IDLE
15:08:50 DEBUG AppSettings$1.v:108 - looking for next job
15:08:50 DEBUG AppSettings$1.v:108 - non persistent result null
15:08:50 DEBUG AppSettings$1.v:108 - persistent result null
15:08:50 DEBUG AppSettings$1.d:92 - keep alive: 1581364122228571687
15:08:50 DEBUG AppSettings$1.d:92 - Consumer idle, will kill? false . isRunning: true
15:08:51 DEBUG AppSettings$1.d:92 - add delayed message Command[2] at time 1581364122228571687
15:08:51 DEBUG AppSettings$1.d:92 - poke consumer manager at 1581364122228571687
15:08:51 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364062254823981
15:08:51 DEBUG AppSettings$1.d:92 - [priority_mq] looking for next message at time 1581364062255034918
15:08:51 DEBUG AppSettings$1.d:92 - returning next ready at 59973747706 ns
15:08:51 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364062255034918
15:08:51 DEBUG AppSettings$1.d:92 - [consumer_4] remove message null
15:08:51 DEBUG AppSettings$1.d:92 - [priority_mq] next delayed job null
15:08:51 DEBUG AppSettings$1.d:92 - [consumer_4] will wait on the lock until 1581364122228571687
15:08:51 DEBUG AppSettings$1.d:92 - [queue_RUN_JOB_RESULT_6] remove message null
15:08:51 DEBUG AppSettings$1.d:92 - [queue_CONSTRAINT_CHANGE_2] remove message null
15:08:51 DEBUG AppSettings$1.d:92 - [queue_ADD_JOB_3] remove message null
15:08:51 DEBUG AppSettings$1.d:92 - [queue_JOB_CONSUMER_IDLE_5] remove message null
15:08:51 DEBUG AppSettings$1.v:108 - joq idle. running:? true
15:08:51 DEBUG AppSettings$1.d:92 - Job queue idle. next job at: null
15:08:51 DEBUG AppSettings$1.d:92 - [priority_mq] did on idle post a message? false
15:09:09 DEBUG GpsMainActivity.populateProfilesList:571 - Current profile:Default Profile
15:09:09 DEBUG Systems.hasUserGrantedPermission:162 - Permission android.permission.ACCESS_COARSE_LOCATION : true
15:09:09 DEBUG Systems.hasUserGrantedPermission:162 - Permission android.permission.ACCESS_FINE_LOCATION : true
15:09:09 DEBUG Systems.hasUserGrantedPermission:162 - Permission android.permission.WRITE_EXTERNAL_STORAGE : true
15:09:09 DEBUG Systems.hasUserGrantedPermission:162 - Permission android.permission.READ_EXTERNAL_STORAGE : true
15:09:09 DEBUG GpsMainActivity.onCreate:116 - Permission check OK
15:09:09 DEBUG GpsMainActivity.onCreate:119 - Start logging on app launch
15:09:09 DEBUG GpsLoggingService.startLogging:391 - .
15:09:09 DEBUG GpsLoggingService.setupAutoSendTimers:309 - Setting up autosend timers. Auto Send Enabled - false, Auto Send Delay - 60.0
15:09:09 INFO  GpsLoggingService.resetCurrentFileName:786 - Filename: 20200210
15:09:09 INFO  GpsLoggingService.notifyClientsStarted:430 - Started
15:09:09 DEBUG GpsLoggingService.notifyByBroadcast:416 - Sending a custom broadcast
15:09:09 INFO  GpsLoggingService.startGpsManager:620 - Requesting GPS location updates
15:09:09 INFO  GpsLoggingService.startGpsManager:629 - Added NMEA listener, new version
15:09:09 INFO  GpsLoggingService.startGpsManager:653 - Requesting cell and wifi location updates
15:09:09 DEBUG GpsMainActivity.populateProfilesList:571 - Current profile:Default Profile
15:09:10 DEBUG GpsMainActivity$12.onServiceConnected:1134 - Connected to GPSLoggingService from MainActivity
15:09:10 DEBUG GpsLoggingService.onLocationChanged:823 - Has description? false, Single point? false, Last timestamp: 1581365330644
15:09:11 DEBUG GeneralLocationListener.onGpsStatusChanged:138 - 20 satellites
15:09:11 DEBUG GpsLoggingService.onLocationChanged:823 - Has description? false, Single point? false, Last timestamp: 1581365330644
15:09:11 DEBUG GpsLoggingService.onLocationChanged:823 - Has description? false, Single point? false, Last timestamp: 1581365330644
15:09:11 DEBUG GeneralLocationListener.onGpsStatusChanged:117 - Fix obtained
15:09:12 DEBUG GpsLoggingService.stopLogging:447 - .
15:09:12 DEBUG GpsLoggingService.stopGpsManager:721 - Removing towerLocationManager updates
15:09:12 DEBUG GpsLoggingService.stopGpsManager:726 - Removing gpsLocationManager updates
15:09:12 INFO  GpsLoggingService.notifyClientsStarted:430 - Stopped
15:09:12 DEBUG GpsLoggingService.notifyByBroadcast:416 - Sending a custom broadcast
15:09:12 DEBUG GpsSimpleViewFragment.onWaitingForLocation:471 - false
15:09:12 DEBUG GpsMainActivity.stopAndUnbindServiceIfRequired:1169 - Stopping the service
15:09:12 WARN  GpsLoggingService.onDestroy:144 - GpsLoggingService is being destroyed by Android OS.
15:09:12 DEBUG GpsMainActivity.stopAndUnbindServiceIfRequired:1169 - Stopping the service
15:09:50 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364122246685374
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] post message Command[2]
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] remove message Command[2]
15:09:51 DEBUG AppSettings$1.d:92 - Consumer has been poked.
15:09:51 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364122259153292
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - consumer manager on idle
15:09:51 DEBUG AppSettings$1.d:92 - [queue_JOB_CONSUMER_IDLE_5] post message com.birbit.android.jobqueue.messaging.message.JobConsumerIdleMessage@64b3d1b
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] will wait on the lock forever
15:09:51 DEBUG AppSettings$1.d:92 - [priority_mq] looking for next message at time 1581364122261023032
15:09:51 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364122261023032
15:09:51 DEBUG AppSettings$1.d:92 - [priority_mq] next delayed job null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_RUN_JOB_RESULT_6] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_CONSTRAINT_CHANGE_2] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_ADD_JOB_3] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_JOB_CONSUMER_IDLE_5] remove message com.birbit.android.jobqueue.messaging.message.JobConsumerIdleMessage@64b3d1b
15:09:51 DEBUG AppSettings$1.d:92 - [priority_mq] consuming message of type JOB_CONSUMER_IDLE
15:09:51 DEBUG AppSettings$1.v:108 - looking for next job
15:09:51 DEBUG AppSettings$1.v:108 - non persistent result null
15:09:51 DEBUG AppSettings$1.v:108 - persistent result null
15:09:51 DEBUG AppSettings$1.d:92 - keep alive: 1581364122228571687
15:09:51 DEBUG AppSettings$1.d:92 - Consumer idle, will kill? true . isRunning: true
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] post message Command[1]
15:09:51 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364122271450116
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] remove message Command[1]
15:09:51 DEBUG AppSettings$1.d:92 - [consumer_4] finished queue
15:09:51 DEBUG AppSettings$1.d:92 - killed consumers. remaining consumers 0
15:09:51 DEBUG AppSettings$1.d:92 - [priority_mq] looking for next message at time 1581364122273434022
15:09:51 DEBUG AppSettings$1.d:92 - flushing messages at time 1581364122273434022
15:09:51 DEBUG AppSettings$1.d:92 - [priority_mq] next delayed job null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_RUN_JOB_RESULT_6] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_CONSTRAINT_CHANGE_2] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_ADD_JOB_3] remove message null
15:09:51 DEBUG AppSettings$1.d:92 - [queue_JOB_CONSUMER_IDLE_5] remove message null
15:09:51 DEBUG AppSettings$1.v:108 - joq idle. running:? true
15:09:51 DEBUG AppSettings$1.d:92 - Job queue idle. next job at: null
15:09:51 DEBUG AppSettings$1.d:92 - [priority_mq] did on idle post a message? false
```

**Comment by 03397** [comment] 2020-02-10 21:34
> Gather logs: https://gpslogger.app/#troubleshooting
> 
> In the meantime I do think this may be activity recognition related. If you disable the activity recognition feature "Don't log if I'm not moving" does the problem go away?

The think is that the problem does not appear immediately when you start the gps logger.
As per ChromoX  the problem initially appears during the phone waking up but also as I already have mentioned during the use of the phone.

**Comment by 03397** [comment] 2020-02-10 21:39
@mendhak 
Have you tested this on an Android 10 phone? Like I have already explained the issue does not appear immediately. If you have tested it successfully then the problem lies to the Pixel 3 hardware accelerometer maybe??

**Comment by FuzzyMistborn** [comment] 2020-02-10 21:42
I had the same issues on my Pixel 3 on Android 10.  I rolled back to 103 and everything is fine.

**Comment by mendhak** [comment] 2020-02-10 22:40
Right I finally got it - I ran it on an Android 10 device and after about 30 minutes the issue appeared.  Unlocking the phone took a few tries.  

However there was nothing weird in the logs.  

If anyone is able to sideload an APK and test, I have one here:  https://github.com/mendhak/gpslogger/releases/tag/v105

In this APK I have simply removed Activity Recognition code.  If removing that feature results in more stable performance, then OK - will have to keep it out until I can find out why there's a problem and how to reinstate it properly.  


Under General, this will appear as version "GPSLogger version 104-noactivity"

**Comment by FuzzyMistborn** [comment] 2020-02-11 00:10
Installed, will report back tomorrow (almost bedtime here) if I notice a lock up when I wake up.

**Comment by ChromoX** [comment] 2020-02-11 00:44
I installed `104-noactivity` and have not had any issues. I'm pretty confident @mendhak has identified the problem area.

**Comment by FuzzyMistborn** [comment] 2020-02-11 02:30
Just had a system ui crash on the no-activity build.  Will see if it happens again

**Comment by ChromoX** [comment] 2020-02-11 03:16
I also had a SystemUI crash on the no-activity build. But it doesn't happen anywhere near as frequently.

**Comment by mendhak** [comment] 2020-02-11 07:21
I got the crash too, while browsing with GPSL in the background, the screen blanked for a bit and the system UI restarted.  

I'm now having a look through here, changes since the last release,

https://github.com/mendhak/gpslogger/compare/v103...master 

to see which other areas could be problem areas.  

I also ran a logcat with the phone connected. 

A problem seems to be with the binder. There are many of these scattered about

```
2020-02-11 06:44:20.163 1384-1480/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 164)
2020-02-11 06:44:20.163 1384-1480/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 168)
2020-02-11 06:44:20.164 1384-1480/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 164)
```

Eventually resulting in

```
2020-02-11 06:45:47.184 1384-1480/? I/ActivityManager: Killing 22810:com.android.systemui/u0a154 (adj -800): scheduleCrash for 'can't deliver broadcast' failed
2020-02-11 06:45:47.185 1384-1480/? W/BroadcastQueue: Failure sending broadcast Intent { act=android.intent.action.CLOSE_SYSTEM_DIALOGS flg=0x50000010 (has extras) }
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:510)
        at android.app.IApplicationThread$Stub$Proxy.scheduleRegisteredReceiver(IApplicationThread.java:1672)
        at com.android.server.am.BroadcastQueue.performReceiveLocked(BroadcastQueue.java:588)
        at com.android.server.am.BroadcastQueue.deliverToRegisteredReceiverLocked(BroadcastQueue.java:814)
        at com.android.server.am.BroadcastQueue.processNextBroadcastLocked(BroadcastQueue.java:990)
        at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:949)
        at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:186)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-02-11 06:45:47.186 1384-1384/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 136)
2020-02-11 06:45:47.188 1384-1480/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 324)
2020-02-11 06:45:47.189 1384-1480/? W/BroadcastQueue: Can't deliver broadcast to com.android.systemui (pid 22810). Crashing it.
2020-02-11 06:45:47.189 1384-1480/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)
2020-02-11 06:45:47.190 1384-1480/? I/ActivityManager: Killing 22810:com.android.systemui/u0a154 (adj -800): scheduleCrash for 'can't deliver broadcast' failed

```

From [what I am reading](https://stackoverflow.com/questions/45432647/android-throw-deadobjectexception-with-log-transaction-failed-on-small-parcel) this may be related to broadcast receivers, so it could be existing code and the problem is with the SDK upgrade.

**Comment by 03397** [comment] 2020-02-11 07:41
This make sense. Just to add further after the upgrade I was getting a lot of timeouts when logger was trying to pinpoint my location. I had to manual reset the gps using an app and the timeouts were dissapeared. 

Do you have any clue why the do not move feature was broken after the upgrade?

**Comment by BlackTowerWA** [comment] 2020-02-11 20:51
I have a Pixel 2 that also has this issue. I noticed the system ui crashes seemed to happen whenever I got a notification (from other apps). I figured the bug might be part of the persistent notification so I turned off the app's notification in the Android App Info and it seems like it no longer hangs and crashes the system ui but will still eventually do something that causes the battery to get warm and used up really fast (I think it worked correctly for about 6 hours) and force killing the app doesn't stop it. I just had to reboot the phone to get it to cool down.

**Comment by mendhak** [comment] 2020-02-11 23:07
Still no answer on what/why.  So as to not leave you hanging I have taken a scattershot approach.  There is a 

[gpslogger-104-no.ac.fg.aid.wk.apk](https://github.com/mendhak/gpslogger/releases/download/v105/gpslogger-104-no.ac.fg.aid.wk.apk) in the [release 105](https://github.com/mendhak/gpslogger/releases/tag/v105).  

In this "-104-no.ac.fg.aid.wk.apk" the odd name indicates I have disabled activity recognition, disabled foregroundservicetype attribute, disabled androidid, disabled week rollover correction.

If the bad behavior doesn't manifest itself I'll slowly restore features until I find out what the culprit is.  Or if this month's awful luck holds, what the culprits are.

**Comment by fred-rum** [comment] 2020-02-12 02:51
I'm glad that there is already some activity on this.  GPS Logger has always been so rock solid for me, so this came as a shock.  I am also having the trouble that the app stops logging GPS info, the phone heats up and runs down the battery, and all apps become very slow to switch between or communicate with.

Other GPS apps also stop tracking, although not necessarily at the exact same time.  I started GPS Logger and also Avenza PDF Maps, and GPS Logger kept logging for an extra 110 seconds after the last data point from Avenza before GPS Logger also stopped.  Running GPS Logger by itself didn't help, though.  It also stopped after a while.  Avenza PDF Maps tracking on its own had no problems.

My phone is a Moto G(4) running Android 7.0.

I couldn't find a way to reset whatever was stuck on my phone, so I had to reboot after each crash.

**Comment by 03397** [comment] 2020-02-12 06:58
> Still no answer on what/why. So as to not leave you hanging I have taken a scattershot approach. There is a
> 
> [gpslogger-104-no.ac.fg.aid.wk.apk](https://github.com/mendhak/gpslogger/releases/download/v105/gpslogger-104-no.ac.fg.aid.wk.apk) in the [release 105](https://github.com/mendhak/gpslogger/releases/tag/v105).
> 
> In this "-104-no.ac.fg.aid.wk.apk" the odd name indicates I have disabled activity recognition, disabled foregroundservicetype attribute, disabled androidid, disabled week rollover correction.
> 
> If the bad behavior doesn't manifest itself I'll slowly restore features until I find out what the culprit is. Or if this month's awful luck holds, what the culprits are.

I have installed the "stripped" version.
After approximately one hour the problem appeared

**Comment by Gunirus** [comment] 2020-02-12 10:14
I have the same problem on a Pixel 3a, but I am not sure it is only related to GPSLogger. Before I saw this issue I also installed [a battery draining app](https://play.google.com/store/apps/details?id=com.lohjason.genericbatterydrainer&hl=en) to see if it was load related. With this app running it is quite easy to reproduce while GPSLogger is active. However, after uninstalling GPSLogger I still see the same problem sometimes when pulling down the notification drawer under high load. It only happens sometimes, but it's definitly not resolved.
I recently upgraded to the february security patch, it might be related? Is anyone else able to reproduce this without having GPSLogger active?

**Comment by BlackTowerWA** [comment] 2020-02-12 17:34
I installed gpslogger-104-no.ac.fg.aid.wk.apk last night and it seemed fixed but I found that it wasn't logging and it turned out the app permissions were set to only allow GPS while the app was open. I changed it to allow always and it started logging again and worked for about 4 hours before locking up and crashing the system ui. Interestingly I used my phone for the first time in a few hours right before I went to lunch and 5 minutes later when I got to my lunch place it had locked and crashed the system ui. Not sure if was coincidence and 4 hours it the lock up "timer", or because I unlocked my phone which made it crash system ui, or moving a significant distance for the first time since always allowing GPS to the app made the app do something that caused it.

**Comment by stephen-hill** [comment] 2020-02-13 11:16
I would like to provide some info as I too may be experiencing problems with the app since the latest update.

Phone: Moto G4 Plus
Android Version: 7.0
App Version: 104

Since the update, at random points during the day, the 1min logging interval to a HTTPS endpoint stops. From this point onwards, the battery capacity of my phone is rapidly reduced. This morning, it took 2.5 hours to reduce my battery by 67%.

The phone UI is randomly unreponsive, and I've had to hard reboot the phone a couple of times.

I'm going to disable the app for a couple of days, and will report back if the problem disappears.

Cheers
Stephen

**Comment by markdepalma** [comment] 2020-02-13 13:18
I am having the same issues. It took my days to figure it out. I finally spent time digging into logcats this morning during my commute and that led me to this app being the culprit. I've disabled the app and the device has been normal since.

**Comment by mendhak** [comment] 2020-02-13 20:40
https://github.com/mendhak/gpslogger/releases/tag/v105

I've completely rolled back v104 and gone all the way back to v103. 
I just amended the target SDK version to 28, and added a FOREGROUND_SERVICE permission (a requirement in SDK 28).  That's all.  I've been running this for a few hours and it seems OK now. 

Everything that I have tried above has not worked.  I'm actually going to push v105 (which is pretty much v103) to the market now.  This means all v104 features will be undone.

**Comment by mendhak** [comment] 2020-02-13 20:42
Feel free to test v105 anyway from the releases link but I'm going to push to the market. There are so many crashes happening, it's really stressing to know this sits unresolved for people for so many days.

**Comment by mendhak** [comment] 2020-02-13 20:50
v105 has been pushed to market

![image](https://user-images.githubusercontent.com/746276/74476985-5969dd00-4ea2-11ea-8e0d-5ebbd12f0cc7.png)

**Comment by 03397** [comment] 2020-02-14 07:09
@mendhak 
Thanks. Reverting back solve the issues.

**Comment by jeffhuang** [comment] 2020-02-14 07:30
Thank you @mendhak for the fast revert. I've had no issues since the latest update. I hope you figure out the root cause. Let us know if you need any help with the debugging, I'm on a Pixel 4.

PS: just want to mention, I've been using gpslogger for 7 years and have had a nearly full set of logs. Thanks so much for your maintenance of it, and it's been super stable especially in the past 5 years or so (before that, it might need a restart every month or so). gpslogger has a shoutout in our paper: https://jeffhuang.com/papers/Rewind_IMWUT19.pdf

**Comment by stephen-hill** [comment] 2020-02-14 12:59
@mendhak

It's probably only been 12 hours, but v105 seems to have resolved the issues I was having.

Cheers
Stephen

**Comment by grandchamp** [comment] 2020-02-15 10:51
Xiaomi Mi 9 with problems also. Mine and my wife's phone started to reboot randomly and crashing apps. I've just updated to the new version and let's see what happens.
The only thing I noted different on the previous version was something named NMEA listener. I don't know if this is related.

**Comment by solidgoldbomb** [comment] 2020-02-16 02:07
Pixel 3a: v104 resulted in multiple system UI crashes and system freezes as others have described above.  v105 has fixed all issues for me.  Long time happy user of gpslogger.  In case this helps narrow down the root cause of the regression in v104, my setup logs to an HTTP custom URL as well as SFTP uploads (using pubkey auth) every 60mins.  Activity Recognition is disabled.

**Comment by mendhak** [comment] 2020-02-29 16:19
Closing this now - will be focusing on trying to reintegrate the changes since November.

**Closed by mendhak** 2020-02-29 16:19 UTC
