### ISSUE TITLE
OpenGTS - too many requests results in "unable to create application data" crash

### ISSUE THREAD

**Issue by edwardmuel** [mendhak/gpslogger#430] opened 2016-04-16 23:02 UTC
I have my gpslogger version 75 configured to log to GPX, KML, and OpenGTS (HTTPS)
I'm currently travelling and the app seems to almost always crash/close when logging the second or third point of data.
I checked the log view but didn't see anything unusual, even just before the app crashed.
I didn't run into any problems if it successfully logged the first few points.
When I was testing at home (logging was started while wifi was connected), I didn't experience any crashes. The main difference here is that I'm not connected to wifi when starting.
Enabling airplane mode and waiting for a few points of data seems to prevent the crash.

Is there any easy way to get crash logs to diagnose the actual problem?

**Comment by mendhak** [comment] 2016-04-16 23:11
Try General settings, then enable debug logs. Then reproduce crash, it
should make a debuglog.txt file. That file you can mail to me gpslogger at
Mendhak.com, or attach to issue

The github released page also has previous versions if it makes a difference

**Comment by edwardmuel** [comment] 2016-04-22 00:06
I have not been able to reproduce the crash yet, but I suspect that it could have something to do with an unstable internet connection. I barely have signal where I am going to be staying (and the data is very slow), but the app isn't crashing.

I have version 76 installed now, but it doesn't look like there are any relevant commits that would have fixed the issue.

If I reproduce the crash, I will send you the debug log.

**Comment by edwardmuel** [comment] 2016-04-23 03:37
I just had a crash after I stopped logging. May or may not be related to the same one I was experiencing. I have the app configured to auto-send on stopping. Will send the debug log as soon as I am able to. The whole log is 24171 lines.
Until I am able to send it out, I'm including the last exception that occurred.
There are two SocketTimeoutExceptions in the log (lines 11227 and 11253) and four SSLExceptions (lines 24079, 24100, 24124, and 24145)
This one had an actual crash dialog, I don't think the other crashes had that.

```
21:02:05 ERROR CustomUrlJob.shouldReRunOnThrowable:92 - Could not send to custom URL
javax.net.ssl.SSLException: Unable to create application data
	at com.android.org.conscrypt.NativeCrypto.SSL_new(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:288) ~[na:0.0]
	at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195) ~[na:0.0]
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148) ~[na:0.0]
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111) ~[na:0.0]
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188) ~[na:0.0]
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127) ~[na:0.0]
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97) ~[na:0.0]
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289) ~[na:0.0]
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241) ~[na:0.0]
	at okhttp3.RealCall.getResponse(RealCall.java:240) ~[na:0.0]
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198) ~[na:0.0]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160) ~[na:0.0]
	at okhttp3.RealCall.execute(RealCall.java:57) ~[na:0.0]
	at com.mendhak.gpslogger.loggers.customurl.CustomUrlJob.onRun(CustomUrlJob.java:69) ~[na:0.0]
	at com.path.android.jobqueue.Job.safeRun(Job.java:145) ~[na:0.0]
	at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:90) ~[na:0.0]
	at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]```

**Comment by edwardmuel** [comment] 2016-04-25 05:34
Here is my log from the other day: [debuglog.2016-04-22.trimmed.txt](https://github.com/mendhak/gpslogger/files/233939/debuglog.2016-04-22.trimmed.txt)

I removed personal information and also removed the following lines:
- `.*onGpsStatusChanged.*\n`
- `.*onLocationChanged.*\n`
- `.*onStatusChanged.*\n`

There is a GpsLoggingService being destroyed warning at 21:02, but I assume that's from me stopping the logging.

There are errors around 19:34 (did not crash) and 21:02 (crashed)
I included 10 minutes before/after the first error area, and 10 minutes before the second error area because that's when the log ended.

I can provide a more complete log if required.

**Comment by mendhak** [comment] 2016-04-25 19:06
OK I think that has made the issue clearer - too many HTTP connections are being issued in one go.   

I have to investigate if OKHTTP is closing connections properly - I hope it is - or if it's a simple matter of too many requests being queued up, which means some throttling needs to be introduced for OpenGTS.  This is because on-stop, the entire GPX file is read, and each point is sent to OpenGTS.

**Comment by mendhak** [comment] 2016-04-25 20:13
The app has default 5 background requests going at a time, I've reduced this to 1.  It is possible that during the send-to-opengts, it was issuing way too many requests simultaneously and this was causing the lockup.  By reducing to 1, it'll be done in a calmer fashion.  

If you're up for some testing, try [this APK](https://www.dropbox.com/s/3tpzn1qviwtqdan/gpslogger-76-issue430.apk?dl=0) ([signature](https://www.dropbox.com/s/4mjoggb7o5g5wa0/gpslogger-76-issue430.apk.asc?dl=0)/[hash](https://www.dropbox.com/s/vj8mxh92uir2jpz/gpslogger-76-issue430.apk.SHA256?dl=0)).  If not, that's OK too, I'll just release this at some point with 1 in place.

Also I suggest you save that debuglog.txt somewhere for a while and turn off debug logging in  your app.  That file will grow like a monster.

**Comment by mendhak** [comment] 2016-05-20 18:05
v77 is in releases and has been published to market, it should show up in a few hours.

**Closed by mendhak** 2016-05-20 18:05 UTC
Labels: bug
