### ISSUE TITLE
Multiple folders on Google Drive with the same name when uploading?

### ISSUE THREAD

**Issue by mehrdadn** [mendhak/gpslogger#588] opened 2017-09-03 02:21 UTC
Every few days I wake up to a new folder made on my Google Drive with the exact same name as the one already there, which the program is supposed to upload into. It seems like every so often the program decides to create a new folder to upload its archive to? I don't understand why this is, since normally it just updates the previous file just fine, but my hunch is that this may occur whenever the connection drops sometime during the upload... maybe it thinks the folder doesn't exist because a connection error, so it creates a new one? I'm not sure, but if you could look into this that would be fantastic. Thank you!

**Comment by mendhak** [comment] 2017-09-03 18:46
I modified the logic, previously it was searching by folder name.  Somehow this must be failing intermittently and no idea why - permissions lost?  

The new logic is to check for the folder ID in preferences and do a basic check against GDrive to see if it's still there. If it doesn't exist, search by name, if still not there, then create it.  

![image](https://user-images.githubusercontent.com/746276/30005710-643ac9d8-90e0-11e7-9174-f82e9accff2b.png)

Here's an APK to test with

[APK](https://drive.google.com/file/d/0B6IOK82n4BkAcm5jRUF5ZGxmYzg/view?usp=sharing), [Signature](https://drive.google.com/file/d/0B6IOK82n4BkANDNXWldRYmZQN0k/view?usp=sharing), [Checksum](https://drive.google.com/file/d/0B6IOK82n4BkAejlqQUowWGNsWHM/view?usp=sharing)

**Comment by mehrdadn** [comment] 2017-09-03 19:47
Thanks for the quick response! I'll install it right away and see if the issue arises again.

**Comment by mehrdadn** [comment] 2017-09-07 10:03
Update: It seems this has solved the folder issue, so it's much better than before, but I noticed it still doesn't always fix the file issue -- I got two ZIP files with the same name in the folder today. Not sure why that would have happened but it seems duplicate files can still get created.

**Comment by rfkinline** [comment] 2017-09-19 16:54
On my end the folder issue started the 7th of September and it is still creating a new folder every time

**Comment by rfkinline** [comment] 2017-09-21 11:48
Update: the system stopped creating every time a copy of the folder. Now it creates one copy (GPSLogger for Android (1)) and stores the files in this folder. The folder in the settings is: "GPSLogger for Android". If I change that to GPSLogger for AndroidT, then the system will create GPSLogger for AndroidT (1)

**Comment by mendhak** [comment] 2017-09-22 17:28
@rfkinline are you seeing this problem with the APK I've posted above or the regular market version?

**Comment by rfkinline** [comment] 2017-09-22 17:41
with the regular App

**Comment by mendhak** [comment] 2017-09-22 17:44
If you are able, try to test with the above APK - it should be more stable now - the testing will help.  Or you can wait a bit eventually I'll release this fix.

**Comment by mendhak** [comment] 2017-11-08 23:01
Eventually, in this case, meant 2 months ->  v90 released to market.

**Comment by mehrdadn** [comment] 2018-07-12 10:01
Hi @mendhak, this issue still isn't fixed unfortunately. Every few weeks I check my Google Drive and I see 2-3 folders by GPSLogger with the same name. I don't know what the edge case is, but it still seems like it sometimes creates a new folder instead of updating an existing one.

**Comment by mehrdadn** [comment] 2018-07-12 10:16
I have a suspicion the problem occurs when there is a network or server error for whatever reason. Namely, what do you do if checking for an existing folder fails? Looking at your code, it seems to me that you [simply assume the folder doesn't exist](/mendhak/gpslogger/blob/4cfe35fb0c5a58ecc5048ae703be021190245975/gpslogger/src/main/java/com/mendhak/gpslogger/senders/googledrive/GoogleDriveJob.java#L257) and therefore you create a new one, hence causing the problem. What I think you would instead want to do is to try again for a few times, unless you know the error is unrecoverable (e.g. access denied due to changed sharing permissions, etc.). And if retrying constantly fails (e.g. network error), I'd treat it as an upload error.

And as to why the retrieve-by-ID would fail, I have no idea... I haven't reinstalled or even changed the app settings in months, but the problem still keeps occurring.

**Comment by rfkinline** [comment] 2018-07-12 10:41
It did work for some time, but it looks like the fix was removed again. I also have multiple directories again,  but I learned to live with it. There are now 4 directories and everything is stored/updated in the last directory. Not sure if it helps. The original directory was created 14Nov17, second and third: 27Mar18. Last and current one 22Apr18. Directories 2 and 3 are empty

**Comment by mendhak** [comment] 2018-07-12 20:15
Hey that is an interesting idea - I wouldn't even have expected such a basic request to fail.  I think the simplest thing I can do here is to allow that particular exception to bubble up.  In turn the bubbling should get captured in the job queue... and in turn allow the next file-upload to do the job.  Or change the job to retry after [a little while](https://github.com/yigit/android-priority-jobqueue/blob/master/examples/twitter/TwitterClient/src/com/birbit/android/jobqueue/examples/twitter/jobs/PostTweetJob.java#L80).

**Comment by mehrdadn** [comment] 2018-07-12 20:30
I don't actually know if it's failing, it's just my hunch that it's failing because of network connectivity or something like that. If you have a way for me to check let me know.

**Comment by xentavo** [comment] 2018-07-12 21:02
You never know with connectivity, but in my case the system has not created a directory in over 4 months. I have the app running 24/7 and I have been moving all over the place. Also why would there be two empty directories? Maybe something to do with time? Here is something curious: The timestamp of those two empty directories is before their time of creation (creation: 6:24, modified 2:38; same day). I was in the same time-zone that day.
[https://imgur.com/Tfgzwhv](url)

**Comment by rfkinline** [comment] 2018-07-12 21:05
Sorry, above message from xentavo should have come from my other github account rfkinline

**Comment by mehrdadn** [comment] 2018-07-13 13:34
There's also another bug I just saw, which is that if I trash the folder it previously uploaded to, it will still continue to receive the uploads, meaning I won't see the uploads in my drive (even if a folder with the correct name already existed there).

It's possible to work around this by discovering the path on every upload, but I feel it might actually mean that using the folder or file IDs is just a bad idea in the first place, and that attempting to discover the path based on the ID might still encounter another edge case I'm not aware of...

**Comment by mendhak** [comment] 2018-07-14 20:21
Storing the folder ID was introduced after the search-by-name kept behaving in strange ways.  It's actually reduced a lot of emails about the Google Drive multiple-folder problem.  So in other words, discovering the path on every upload was introducing more problems than it was solving.

The workaround here would be if you trash the folder, delete it permanently instead; or if you want a fresh start, empty the contents of the folder.

**Comment by mehrdadn** [comment] 2018-07-14 20:35
Well personally I of course realize the workaround, but it's not realistic to expect users to know the bug and the workaround, and to be willing or even able to use this workaround—you're effectively asking the users to stop using the "Trash" feature of Google Drive.

I think there must be a proper solution here, so if you'd like to provider a link or other information, I'm happy to help you figure out a better solution for whatever problems people were experiencing...

**Comment by mendhak** [comment] 2018-07-14 20:58
The problem was exactly the same as described here, just with a higher rate of occurrence among users.  The "GPSLogger for Android" folder was being created multiple times in Google Drive.  The `getFileIdFromFileName` method would do its `/drive/v2/files` request and I believe that's where something was happening; introducing the persisted folder ID helped a lot.  

I say 'believe' because - the difficulty with troubleshooting this is not I don't know how to reproduce it.  Also it's unrealistic to ask users to run a debuglog file for months waiting for the problem to happen again.  

Of course removing the locally stored ID would solve the trashing case at the expense of again increasing the rate of the original issue.   

Yep, any suggestions would be good.  Perhaps extra calls to the Drive API to check that the folder hasn't been trashed.  Requires extra calls.   

Drive REST API v3 has been introduced.  This could be worth trying; from experience Google tend to 'forget' that older versions exist.

This also exists, the Drive [library](https://developers.google.com/drive/android/queries).  I've been avoiding this for a long time since it will increase the APK size.

**Comment by mehrdadn** [comment] 2018-07-14 21:06
OK, I see. Have you tried distinguishing between the different types of errors and handling them differently as I suggested above? I suspect that's the underlying problem's solution, and is likely to address what other users have encountered too. Specifically:
- Errors reported by Google Drive should result in failure to upload (and possibly user notification?)
- Network & other errors should result in a retry with increasing timeouts, bounded by the next upload time
- Non-existent folders/files should result in a new folder/file being created, not an error

**Comment by rfkinline** [comment] 2018-07-14 21:15
As advised I just deleted all the folders (GPSLogger) on google drive (local and cloud). I changed the destination folder in the app to GPS but the system is still using the old folder. Looks like the issue is a bit more complex as I don't want to touch the cash.

**Comment by mehrdadn** [comment] 2018-07-14 21:17
@rfkinline Have you ensured the folder is not in your Trash? Merely "deleting" them would not be enough if it sends the folder to Trash. The fact that the name change doesn't help suggests that the ID is still being used, which I guess supports my claim that the ID should not be used naively like this.

@mendhak:
As for optimization & reducing the number of API calls:

Note that you cannot check to see if the folder is trashed, because one of its ancestors may have been trashed instead—or it may not have been even trashed, but moved. Furthermore, Google Drive's file system model supports multiple parent folders, and while I'm not too familiar with how it works, I don't think it means that it doesn't even makes sense to ask if the folder is trashed, since it may be trashed via path A but not via path B.

You probably can't _reduce_ the number of API calls, because you are required to traverse all components of the path to make sure they are correct. However, you _can_ parallelize them if you cache the IDs of all the folders in the path. (This is a bit tedious as it requires retrying until you retrieve all of the path components' parents. And again, you would need to distinguish between network errors and API errors.) I would not perform this optimization in the beginning, though... I would first get it correct and then try to optimize once I know the behavior is correct, because it's likely that the optimization will introduce bugs of its own, and it won't be clear where the problem is.

**Comment by rfkinline** [comment] 2018-07-14 21:22
Yes, I emptied the trash folder before changing the folder in the app.

**Comment by rfkinline** [comment] 2018-07-14 21:30
Sorry. 
Old in the app = GPSlogger. Old in Google Drive  = GPSLogger, GPSLogger(1), GPSLogger(2) and GPSLogger(3). 
New in the app = GPS. New in Google Drive  = GPSLogger, GPSLogger(1)
(after deleting and also re-testing the connection): https://imgur.com/igUcpM4,

**Comment by mehrdadn** [comment] 2018-07-14 21:33
Huh, so basically the name change in the app isn't taking effect? That seems like a second bug...

**Comment by rfkinline** [comment] 2018-07-14 21:37
Correct. It might be that it is the cache, but I am afraid of emptying it as it might mess up my settings.

**Comment by rfkinline** [comment] 2018-07-14 21:48
Some screenshots:
https://imgur.com/6iWTm4c
https://imgur.com/pVMaL9R

**Comment by mendhak** [comment] 2018-07-14 22:02
Ah twofold bug :disappointed: .  When changing the folder name the old ID is still cached. Rename should have cleared the ID, so I'll add this to the list if still going with the caching-ID route. 

The other issue is - Google Drive even after you *permanently* delete something... doesn't delete it.  The API will still report that a resource exists and it will continue sending your uploads to that location.  There is some internal schedule that Google Drive follows at which point the object is actually deleted.  

I have a crude workaround for you.  In the GPSLogger folder on your phone, create a file called `gpslogger.properties` and in that put

`GDRIVE_FOLDER_ID=`

Close everything, reopen GPSLogger.  This will cause your cached ID to be reset. Go back and delete that file.  Now try your upload again.

**Comment by mendhak** [comment] 2018-07-21 21:51
Working on a new branch - [gdrivefix](https://github.com/mendhak/gpslogger/compare/gdrivefix?expand=1).

So far I've:

* Switched to Google Drive API v3.   
* Removed the cached folder ID - now the folder will be searched each time.  If you change the folder name it should reflect right away.
* Removed `catch` around the ID search, so now the exception will bubble and cause the Job Queue re-queues it.  This is new logic, haven't tried before.  I hope this should cater to the problem that may have been occurring - search for folder failing, causing it to be recreated.  But now the search failure should be retried.  
* Latest version of Job Queue - supports exponential backoff.  Applied to Google Drive at 3s.

If you're interested you can try to sideload.  I will be testing at home. 

[APK](https://drive.google.com/file/d/1cd3PDRIJcYLwFatB1SkW9zHjl7cgeB6c/view?usp=sharing), [signature](https://drive.google.com/file/d/1VkVWBo93Qfv0-PhlWfF2MnGT-I9FuFmJ/view?usp=sharing), [checksum](https://drive.google.com/file/d/1qnswdl9oxtbKmTkmXJT68IHep8EX1qTq/view?usp=sharing)

**Comment by rfkinline** [comment] 2018-07-21 21:56
Great!. I will test too and a second / clean android phone

**Comment by mehrdadn** [comment] 2018-07-21 22:00
Oh cool, thanks! I'll check it out.

**Comment by rfkinline** [comment] 2018-07-24 11:23
Feedback: it works like a charm. 
I have now GPS logger running on 2 phones and I noticed that on one phone the battery usage is 20% (600mAH) and on the other one 5% (160mAH). With exactly the same settings. Is this of any use for you?

**Comment by mehrdadn** [comment] 2018-07-24 18:45
It does seem to be working for me as well, but it seems too early to tell for sure—it usually took a few weeks to start misbehaving, so it's hard to tell right now.

**Comment by mehrdadn** [comment] 2018-08-12 07:13
Yeah I think the battery issue was unrelated. The patch is all good as far as I can tell so far :) but if I see anything to the contrary I will let you know.

**Comment by mendhak** [comment] 2018-09-30 20:55
Fixed in v96, will reopen if it happens again

**Closed by mendhak** 2018-09-30 20:55 UTC
