### ISSUE TITLE
Protocol to URL is not functionning

### ISSUE THREAD

**Issue by Mecky99** [mendhak/gpslogger#663] opened 2018-07-20 16:44 UTC
Using version 95 on a Samsung S7 Android 8.0.0 version

URL used :

https://project-gc.com/api/UserLocation/Update/?protocol=1&uid=********&latitude=%LAT&longitude=%LON&acc=%ACC&ts=%TIMESTAMP&token=********&nid=****&enable=1

HTTP-Methode : GET

SSL-Certificate : OK

HTTP-TEST :

Error message (unexpected code response) : Invalid coordinates

Where is the problem ???

Thanks for supporting

**Comment by mendhak** [comment] 2018-07-20 17:06
Duplicate of #661 - basically the test is working (you got a response) but is worded too confusingly.  Will remove this test in the next release.

**Closed by mendhak** 2018-07-20 17:06 UTC
