### ISSUE TITLE
sometimes auto-upload to Openstreetmap does not work

### ISSUE THREAD

**Issue by PontiacCZ** [mendhak/gpslogger#719] opened 2019-02-15 08:03 UTC
We already discussed this in a closed issue about a year ago but this time my situation is a bit different - I have a new phone (Cat S61 with Android 8.1) so I am opening a new one.

Yesterday I made a couple of tracklogs, I was on mobile data all the time. The last tracklog did not get automatically uploaded to the OSM server:

![obrazek](https://user-images.githubusercontent.com/9153595/52842442-691fdb80-30ff-11e9-8617-2e3b876a91a8.png)

All previous logs are [there](https://www.openstreetmap.org/user/Pontiac_CZ/traces):

![obrazek](https://user-images.githubusercontent.com/9153595/52842464-78068e00-30ff-11e9-9752-a9cbc48a9ef0.png)

Sure there might have been a cellular data issue when GPSlogger was attempting to send the last tracklog but it even did not get uploaded today when I launched the application to make the above screenshot (I am on wi-fi here).

This already happened to me a few days ago so I turned on generating debug logs. I am ready to send them to you.

**Comment by mendhak** [comment] 2019-02-15 21:44
OK yes if you do have a debuglog already then can you send it.  You can mail it to `gpslogger@mendhak.com`

**Comment by PontiacCZ** [comment] 2019-02-17 10:44
It just have been sent. :)

**Comment by mendhak** [comment] 2019-03-02 11:00
I had a look at the debuglog file sent, it looks like all files were sent to OSM without errors.  In this log file you sent,  were any of these files _not_ sent?    

    └─▪ grep --only-matching -i 'filename:.*' issue719.debuglog.txt | sort --unique
    FileName:750 - Filename: 20190216072352
    FileName:750 - Filename: 20190216133059
    FileName:750 - Filename: 20190216154332
    FileName:750 - Filename: 20190216182723


    └─▪ grep --only-matching -i 'sending file.*' issue719.debuglog.txt | sort --unique
    sending file 20190216072352
    sending file 20190216133059
    sending file 20190216154332
    sending file 20190216182723

**Comment by PontiacCZ** [comment] 2019-03-02 12:21
They all were uploaded.

![obrazek](https://user-images.githubusercontent.com/9153595/53681726-de89cf80-3ced-11e9-9370-04420f91badc.png)

**Comment by mendhak** [comment] 2019-03-02 12:30
OK I meant earlier what you could do is have the debug log running but only send it when an upload fails.  The upload failure is likely to be caused by some error (or failed after x retries), and that failure or error or retry condition will be in the debug log, then we can figure out - why did the upload fail.  

If everything has been fine since the last failure, the cause of failure can be simple things like - you're connected to a network and Android incorrectly reports that there is a working data connection.  

![image](https://user-images.githubusercontent.com/746276/53681818-b8acfc80-3ce6-11e9-9971-12baa3084307.png)

This can be most apparent when connected to a data point with a captive portal or even if the ISP is undergoing some maintenance.  

The other fault may be with OSM, if they are in the middle of a maintenance window then yes uploads can fail, I've added a retry logic but that can only try a few times.  

If the upload failure is regular, it's something network related, unlikely to be OSM.

**Comment by PontiacCZ** [comment] 2019-03-02 17:11
Since GPSlogger is able to detect that a file upload failed - how about to display on the main screen some diagnostic info about the upload process? I would love to know what actually happened. It is frustrating to accidentally find out later that a particular tracklog is not in Openstreetmap traces...

It could look like this:
![obrazek](https://user-images.githubusercontent.com/9153595/53685048-b31adb00-3d15-11e9-9d7e-53e789d853a2.png)

**Comment by mendhak** [comment] 2019-03-02 17:48
Hey I've actually experimented with that before! An area in simple-view where the latest problem message is shown.  This didn't work out well, because problems relevant to users became overwritten or weren't seen in time.  

So for that reason, the log view is a better option.  Although it too has a buffer (I can't keep too many lines in there as it requires memory use) it has a greater chance that the user will see an error message in there from a failed action

**Comment by PontiacCZ** [comment] 2019-03-03 21:10
Thanks for the suggestion. Today I made four tracklogs. After a stop I always switched to the log view. And it really helped me to find out that the third tracklog failed to upload! I was on a place with bad cell coverage. I needed to wait for about 15 or 20 seconds (due to those retries, right?) but I got this:

![obrazek](https://user-images.githubusercontent.com/9153595/53701271-7f19e580-3dfb-11e9-8eae-b356093f3043.png)

Perfect, this way I will know whether there is a problem sending the file to the OSM.

Well, actually one thought: if all goes well, there is nothing about it in the log. I only see:
```
16:57 Auto-sending file xxxxxxxxxxx
16:57 Zipping file
16:57 Stopped
```

Could you add a log entry in case of a successful upload? (maybe in green this time) I would know that the file has been uploaded and I don't have to wait any longer for an error.

And a second thought: the GPSlogger tries a few times and then eventually gives up. That's OK. But since it knows that the file has failed sending to the server how about tag it as FAILED and try next time I run GPSlogger? It does not do it currently - on the OSM server I still only see the 1st, 2nd and 4th tracklog. Besides that, I am running the GPSlogger now at home on wi-fi but still it does not upload the failed no. 3. (I am going to send it manually now)

**Comment by mendhak** [comment] 2019-03-27 22:13
I've set it as info so all file uploads should now appear in log view, but not in green - that's specially reserved.

The library I'm using does allow for retries with exponential backoff so I've just added that in as well. 

That's likely the safest way to do retries.  Retrying indefinitely would cause battery drain since some condition needs to be met and right now that check is internet connectivity, but seems like there's no way of knowing if it's reliable enough.  The exponential should help a bit as it increases the gap between retries but don't want to retry too much, especially in isolated regions.

**Comment by PontiacCZ** [comment] 2019-03-27 22:23
Thank you very much for your work! I am going to test it thoroughly when I get the new version. :-)

**Comment by mendhak** [comment] 2019-03-27 22:29
Here's an APK if you want to sideload and test it now.   Otherwise it'll be in next play store update.

[APK](https://drive.google.com/file/d/1AIKjc7jzUyoaL2COOXCdoMKj4NZ_31aC/view?usp=sharing), 
[signature](https://drive.google.com/file/d/1kOpV29S_TQuxt_pSQL-z2wmYfd7-YJJY/view?usp=sharing),
[checksum](https://drive.google.com/file/d/1a852eHMsg17aX4F8LYJE46HEiNaL25H8/view?usp=sharing)

**Comment by mendhak** [comment] 2019-03-28 20:21
OK I'm going to try using Github better - I've now created a prerelease with the APK, Signature, Checksum attached. 

https://github.com/mendhak/gpslogger/releases/tag/v101

It's probably better to use Github for this than my personal Google Drive, at least it's in a 'central' place

**Comment by PontiacCZ** [comment] 2019-03-28 20:33
I do not have experience with sideloading - if I download and install the APK, the automatic update from Google Play won't get suppressed, will it?

**Comment by mendhak** [comment] 2019-03-28 20:39
Hey that's correct - if you install the APK I've uploaded then you'll still Google Play store updates, because I signed it with my release key.

**Comment by PontiacCZ** [comment] 2019-03-28 20:50
OK, I seem to have installed it. It says "GPSLogger version 100-milestone101".

Looking forward to testing. :-)

**Comment by mendhak** [comment] 2019-04-14 16:50
v101 pushed to market.

**Closed by mendhak** 2019-04-14 16:50 UTC
