### ISSUE TITLE
.GPX file malformed; has multiple <?xml> and <gpx> elements

### ISSUE THREAD

**Issue by GuyGonJin** [mendhak/gpslogger#594] opened 2017-11-01 18:33 UTC
I keep GPSLogger on 24 hrs per day every day. I use it to track my movements for business logging purposes. At the end of each day, GPSLogger automatically uploads the track files to DropBox and I keep them in long-term archive. It works great for this purpose and I really appreciate the program.

The problem I have is that the .GPX files are often malformed; they have multiple \<?xml\> and \<gpx\> elements. I.e., there is a proper leading \<?xml version="1.0" encoding="UTF-8" ?\> element followed by a proper \<gpx ...\> element and then a \<trk\>, \<trkseg\> and multiple \<trkpt\> elements. All good so far.

Then, part way into the file, there will be terminating elements \</trkseg\>, \</trk\>, \</gpx\> followed (improperly) immediately by another \<?xml ...\> element then a \<gpx ...\> element then another \<trk\> and \<trkseg\> and so-on. Essentially the second \<?xml\> and \<gpx\> elements create the contents of a second entire .GPX file, but it is present within an already existing .GPX file. This can happen multiple times, ending up with 2 or 3 or more file contents within a single file.

The .GPX files are unreadable by Garmin MapSource - I must manually edit the files to remove the extra elements so that there is just a single \<?xml\> and \<gpx\> element.

[20171030.gpx.txt](https://github.com/mendhak/gpslogger/files/1435221/20171030.gpx.txt)
[20171031.gpx.txt](https://github.com/mendhak/gpslogger/files/1435222/20171031.gpx.txt)

I am attaching 2 example files that exhibit this problem. The one for 10/30 has 2 \<gpx\> elements, for 10/31 there are 3 \<gpx\> elements within one file. Note that I have manually edited the files to remove leading and trailing \<trkpt\> elements (where my house is located) but otherwise the files are exactly as written by GPSLogger. Also note that I had to add .TXT suffix so that I would be allowed to attach them here.

Please help to eliminate this problem with the way that GPSLogger writes malformed files. It takes a lot of extra time to work-around this issue and makes the output from the app difficult to use.

Thanks -
Guy

**Comment by mendhak** [comment] 2017-11-02 00:02
What phone do you have, and what's the os version on it? 

These malformed files, are they malformed when you download them from Dropbox or after you viewing them on the phone directly?

**Comment by GuyGonJin** [comment] 2017-11-02 01:14
Phone is Motorola Moto G5 Plus. OS is Android version 7.0. The phone is new as of about 3 weeks ago.

I also had this same problem, albeit less often, on my old phone, which was a Motorola Moto G, Android version 5.1.

The files are malformed as stored in the file system of the phone itself, apparently as written by GPSLogger. I can look at the files via an editor resident on the phone and see the multiple \<?xml\> and \<gpx\> elements. Also I can access the phone's storage via a USB cable and a text editor on my computer and also see the malformed format in the files.

BTW I have .CSV and .KML files that are written by GPSLogger at the same time as the .GPX files, containing the same data. I have looked at the .CSV and .KML files with a text editor and I do not see evidence of multiple headers or multiple \<?xml\> elements and the like, as there are in the .GPX files.

Thanks for your attention to this issue.

Guy

**Comment by mendhak** [comment] 2017-11-06 23:15
So the bit that adds that `<gpx...` to the file is [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java#L201-L214) - the only way this would happen then is if the `File.exists()` is false.

So this could be some kind of filesystem level problem.  For example - any operations which may be locking on to the storage?  Is the app configured to write to internal storage or SD card?  If it's the SD card, then is it the same SD card used in both phones?  Further on, if it's the SD card, does setting GPSLogger back to internal, does the problem disappear?

**Comment by mendhak** [comment] 2017-11-26 22:27
Tried a lot, cannot reproduce anywhere.  I even managed to track someone down with a G5 Plus.  

I've done some digging into the source as well, pushed a commit with [isFile instead of exists](https://github.com/mendhak/gpslogger/commit/f1a49d04058ba3f91491d38f42fdc0b933140896) - as they are two different operations.  

If you are able to sideload APKs you can try this out

[APK](https://drive.google.com/file/d/1NKbxQw14lSqPPnozNVPviHG2WAHXtsKa/view?usp=sharing), [Signature](https://drive.google.com/file/d/1D9MkAPrhFLcC5oPmWc4oQeXKoDcZ70Xo/view?usp=sharing), [Checksum](https://drive.google.com/file/d/11BJ-kD9aWBnjPFJROMZXTate6MI3vY1r/view?usp=sharing)

**Comment by mendhak** [comment] 2018-01-11 22:38
v91 is released to market.

**Comment by mendhak** [comment] 2018-03-16 07:34
Another user via mail has reported - issue still occurring (strangely, also a Moto G5...)  So the file.isfile did not work either. 

I had a stray thought - what if I did multiple File exist and isFIle checks.  eg

    if ( file.exists() || file.exists() || file.exists() ... )

**Comment by GuyGonJin** [comment] 2018-03-16 11:14
Hello:

Thanks for the info. Yes, I figured others must have the same issue since
it happens all the time with my phone, and also on my previous phone. I
hope you find a solution; I need to fix approx half of the files that
gpslogger produces.

Thanks much -

Guy

**Comment by mendhak** [comment] 2018-03-18 19:14
Unfortunately it's all guesswork.  I've now made [another attempt](https://github.com/mendhak/gpslogger/commit/c12f0c661b1eb943cc2cc4d99f6f8b145d72a2f3) by checking for the file in 3 different ways.

It would be useful if you could test the APK I'm posting here:

[APK](https://drive.google.com/file/d/1-ihA3zhDbGrHSlNOkqBbGw9i5KRM2Do7/view?usp=sharing), [Signature](https://drive.google.com/file/d/1wn5xqOj26vYMcFA6z7wuiDfsKUohUJ9n/view?usp=sharing) ,  [Checksum](https://drive.google.com/file/d/13wT5_gLFNQEBjsf24hBp7IZXD5Vmw6ZB/view?usp=sharing)

**Comment by GuyGonJin** [comment] 2018-03-19 04:01
Hello:

I just installed your "gpslogger-93-issue594.apk". I will pay attention to
the files that it produces and let you know what I observe.

Thanks -

Guy




*Start Your Own Adventure Tree Climbing Program. See YourAdventureTree.org
<http://YourAdventureTree.org>*

*Kids Climb Trees and Learn Cool Science at ScienceInATree.org
<http://ScienceInATree.org>*





*Adventure TreeHave Fun - Learn - Grow AdventureTree.org
<http://AdventureTree.org>508-243-5957  cell phoneIthaca, NY*

**Comment by gergelyimre** [comment] 2018-03-19 09:39
I also installed the gpslogger-93-issue594.apk on my Moto G5. I'll make a 5h trip today so I will test it then. I'll let you know.

**Comment by gergelyimre** [comment] 2018-03-20 07:53
Looks like the GPX file it generated is valid, I could import it on Strava, Endomondo and RouteCoverter java app. For the KML file, it said it was invalid. The CSV file I was able to convert to GPX with an online converter, so I would say that was correct, too.

This workaround with the third checking method seems to work.

**Comment by mendhak** [comment] 2018-03-20 08:01
I am somewhat happy that this seems to have done the trick.  I am also somewhat distressed that this worked. 

I was doing a little more searching and I am not sure but this bug on Oracle JDK might be related due to the customer workaround mentioned, although the bug is marked as resolved - https://bugs.java.com/view_bug.do?bug_id=6191254

I'll add this check to the other logfile types and eventually this should make its way into v94.  

- [ ] Add Files.actuallyExists check to all logging types
- [ ] Post APK if v94 delayed

**Comment by GuyGonJin** [comment] 2018-03-20 13:01
Hello:

I am able to check once per day if the GPX file is good or bad. I leave
GPSLogger running all day, every day, and the program automatically uploads
GPX, CSV and KML files via DropBox every 24 hours.

The GPX file for yesterday was good; there was not an extra <trkseg>
element. However, this is not a definitive determination. Approx 50% to 70%
of the GPX files are good. Sometimes I will go many days until I encounter
a bad one. Often a bad file is a larger file on a day when I did lots of
traveling.

I will continue to check and I will let you know if I continue to get good
files or if I encounter a bad file that contains extra <trkseg> elements.

Thanks for your work -

Guy




*Start Your Own Adventure Tree Climbing Program. See YourAdventureTree.org
<http://YourAdventureTree.org>*

*Kids Climb Trees and Learn Cool Science at ScienceInATree.org
<http://ScienceInATree.org>*





*Adventure TreeHave Fun - Learn - Grow AdventureTree.org
<http://AdventureTree.org>508-243-5957  cell phoneIthaca, NY*

**Comment by mendhak** [comment] 2018-03-21 19:15
Yes that's fine - I'll just keep this issue open for a while. 

Eventually I'll merge this branch in anyway - since worst case it doesn't do anything at all. 

https://github.com/mendhak/gpslogger/tree/issue594

**Comment by GuyGonJin** [comment] 2018-03-23 14:33
Hello:

So far there have been no problems. Since I installed the prototype APK,
GPSLogger has created 4 GPX files, each for a full day. All of the GPX
files have been good and did not contain the extra "<?xml ..." file
initialization code.

I will keep you informed if I encounter a bad file.

Thanks -

Guy




*Start Your Own Adventure Tree Climbing Program. See YourAdventureTree.org
<http://YourAdventureTree.org>*

*Kids Climb Trees and Learn Cool Science at ScienceInATree.org
<http://ScienceInATree.org>*





*Adventure TreeHave Fun - Learn - Grow AdventureTree.org
<http://AdventureTree.org>508-243-5957  cell phoneIthaca, NY*

**Comment by mendhak** [comment] 2018-03-26 21:37
v94 released anyway (for the start-on-app-launch bugfix).  I'll still keep this open

**Comment by GuyGonJin** [comment] 2018-03-29 14:14
Hello:

I am currently on a trip with GPSLogger creating large files because of the
long distances that I am traveling. Prior to your bug fix, there would be a
high probability that extra <?xml elements would be created in the GPX
file. However there have been no problems with the GPX files. This is now
10 days and 10 GPX files when there have been no problems.

If the bug happens again then I will let you know. But it seems like the
big is fixed. Thank you for your help with this problem.

Best -

Guy




*Start Your Own Adventure Tree Climbing Program. See YourAdventureTree.org
<http://YourAdventureTree.org>*

*Kids Climb Trees and Learn Cool Science at ScienceInATree.org
<http://ScienceInATree.org>*





*Adventure TreeHave Fun - Learn - Grow AdventureTree.org
<http://AdventureTree.org>508-243-5957  cell phoneIthaca, NY*

**Comment by mendhak** [comment] 2018-03-29 17:56
Thanks for the extensive testing.  I'll close this one now.  If it happens again please create a new issue we can reference this from there.

**Closed by mendhak** 2018-03-29 17:56 UTC
