### ISSUE TITLE
V111 problem - logging stops when using Hungarian locale

### ISSUE THREAD

**Issue by blaszlo71** [mendhak/gpslogger#885] opened 2021-06-11 16:39 UTC
Can't find position, not record. Nor with default settings. It worked perfectly and stabile v110. 
![IMG_20210612_173234](https://user-images.githubusercontent.com/32165794/121781273-45bcac80-cba4-11eb-810a-a6d69ffb1a13.jpg)

**Comment by mendhak** [comment] 2021-10-30 16:45
I missed this one oops!  That line there indicates some kind of error. You'd need to enable debug logging and have a look at the file to see what error is being thrown. 

See: https://gpslogger.app/#troubleshooting

**Comment by blaszlo71** [comment] 2021-10-31 05:44
I created a debug file. From line 53?
[debuglog.txt](https://github.com/mendhak/gpslogger/files/7448176/debuglog.txt)

**Comment by mendhak** [comment] 2021-10-31 13:04
Got it!  Here's the culprit. 


```
java.util.UnknownFormatConversionException: Conversion = 'ó'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2782) ~[na:0.0]
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2812) ~[na:0.0]
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625) ~[na:0.0]
	at java.util.Formatter.parse(Formatter.java:2558) ~[na:0.0]
	at java.util.Formatter.format(Formatter.java:2505) ~[na:0.0]
	at java.util.Formatter.format(Formatter.java:2459) ~[na:0.0]
	at java.lang.String.format(String.java:2870) ~[na:0.0]
	at com.mendhak.gpslogger.common.Strings.getDescriptiveDurationString(Strings.java:99) ~[na:0.0]
	at com.mendhak.gpslogger.GpsLoggingService.getNotification(GpsLoggingService.java:507) ~[na:0.0]
	at com.mendhak.gpslogger.GpsLoggingService.showNotification(GpsLoggingService.java:565) ~[na:0.0]
	at com.mendhak.gpslogger.GpsLoggingService.onLocationChanged(GpsLoggingService.java:898) ~[na:0.0]
	at com.mendhak.gpslogger.GeneralLocationListener.onLocationChanged(GeneralLocationListener.java:72) ~[na:0.0]
	at android.location.LocationManager$LocationListenerTransport.acceptLocation(LocationManager.java:2742) ~[na:0.0]
	at android.location.LocationManager$LocationListenerTransport.lambda$enkW18B0WwpQkSIMmVChmQ2YwC8(Unknown Source:0) ~[na:0.0]
	at android.location.-$$Lambda$LocationManager$LocationListenerTransport$enkW18B0WwpQkSIMmVChmQ2YwC8.accept(Unknown Source:6) ~[na:0.0]
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292) ~[na:0.0]
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201) ~[na:0.0]
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:938) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:99) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:236) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:7864) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011) ~[na:0.0]
```

The problem is happening here, 

https://github.com/mendhak/gpslogger/blob/fcd4e55985e55f69716c10ff99585b6aec100fb1/gpslogger/src/main/java/com/mendhak/gpslogger/common/Strings.java#L99-L100

and I think it's because the string format is coming from here, the `%s` is missing. 

https://github.com/mendhak/gpslogger/blob/fcd4e55985e55f69716c10ff99585b6aec100fb1/gpslogger/src/main/res/values-hu/strings.xml#L87

**Comment by mendhak** [comment] 2021-10-31 13:14
OK the fix is now pushed and I've tagged it as well so it should go in with the [v119 release](https://github.com/mendhak/gpslogger/releases/tag/v119). 

https://github.com/mendhak/gpslogger/blob/7555063e86d08c7a4132624f526eb06f4af49b81/gpslogger/src/main/res/values-hu/strings.xml#L87

**Comment by blaszlo71** [comment] 2021-10-31 15:17
You were fast. I tried it. Works well. THX. Sorry for the translation error.

**Comment by mendhak** [comment] 2021-11-11 22:40
v119 is now on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [in the releases](https://github.com/mendhak/gpslogger/releases/tag/v119).  I'm going around and closing some issues.

**Closed by mendhak** 2021-11-11 22:40 UTC
