### ISSUE TITLE
No "Discard offline locations" toggle, but it does anyway

### ISSUE THREAD

**Issue by kwagnitz** [mendhak/gpslogger#1037] opened 2022-12-24 10:42 UTC
I'm using the custom URL feature, sending to my own hosted server and putting the locations in a DB for display on an OSM map.  Works fine.
However it doesn't send cached locations if network connectivity is lost.  I need it to.
-I tried this two ways: going into aeroplane mode and out; and connecting the phone's WiFi to my caravan homemade gadget which doesn't give Internet access.

I can't find the "Discard offline locations" toggle mentioned in documentation.  Has it been removed?
GPSLogger version is 124.  Phone is SGS9, Android 10.

**Comment by mendhak** [comment] 2022-12-24 21:44
The discard offline feature hasn't been released yet, that will be in the next release (no timeline).   The normal behavior is that if you're offline, locations do get cached then sent later.  If that's not working you'll want to have a look at the 'log view' to see if there are any errors being thrown when you're expecting nothing to be happening, that could indicate that the device _thinks_ you have internet access but actually you don't.   You can also try a debug log as shown in the troubleshooting section.

**Comment by kwagnitz** [comment] 2022-12-24 23:44
Thanks for the quick reply.  I will try some logging.
-It is confusing to have the current documentation contain features not in the current released version.

**Comment by mendhak** [comment] 2022-12-24 23:51
Yes I probably should have added that in later, lesson for next time,  it was the simplest way to manage the pull request with my limited time.

**Comment by dborie** [comment] 2022-12-25 02:31
Hi there, 
I'm just facing this "issue" today, it seem that, somehow, my phone turn offline this morning and log *a lot* of location, as for many hours now I got url push every seconds for many points (more than one per sec)
![image](https://user-images.githubusercontent.com/49395531/209455318-13e4a7f4-78b9-46ac-87f7-b29b0e86f470.png)

This may be caused by using passive record that I've just try to test, I'm not sure

But since, this is basically stuck, is there a way to make it faster if I cant discard them? (I would be a bit annoying to have to drop all the app data just for this :/)

**Comment by mendhak** [comment] 2022-12-25 08:10
There's no simple way I can think of, because the offline jobs that get created aren't direct files on disk as far as I've seen. You could try saving the profile which gives you a file with the various properties in it, but not all properties. Then reset the app and restore the profile file.  But you'd still have to look around and restore missing properties like passwords.

**Comment by dborie** [comment] 2022-12-25 08:57
Still way better than having to reset everything as I was planning :)
I did not know this feature was a thing, thanks a lot for the tip!

**Comment by kwagnitz** [comment] 2022-12-26 00:29
Last night on the xmas dinner trip to relatives, I put the phone in aeroplane mode for part of the drive, both ways.
Log view going there, detailed view coming home, then app closed, as I normally use it.
The whole trip was recorded correctly!!!   No idea why the change in behaviour.

So maybe close this issue as unable to reproduce.  I'll revisit it if it happens again (and try logging).

**Comment by mendhak** [comment] 2023-01-01 20:06
v125 is now in [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [release](https://github.com/mendhak/gpslogger/releases/tag/v125).

**Closed by mendhak** 2023-01-01 20:06 UTC

**Comment by kwagnitz** [comment] 2023-01-01 22:32
Installed 125.  Can confirm that the "Discard offline locations" toggle now appears on the custom URL page.
(I will leave it off.)
