### ISSUE TITLE
missing function: delete log files

### ISSUE THREAD

**Issue by fneitzel** [mendhak/gpslogger#352] opened 2015-09-08 14:58 UTC
Hi there!

Really great app. 
Is it possible to add an automatical remove for log files after they uploaded?
I couldn't find any set up for this.

Best regards

**Comment by mendhak** [comment] 2015-09-08 15:09
Uploads happen in parallel with the file writing, that means they can happen within second or within hours of a log being written (based on internet connectivity, schedule, naming).  In turn that means that deleting a file after it is uploaded will cause data loss.  Also, in the case of Dropbox/GDrive it would cause data loss online as the same file is being overwritten with different contents.

**Comment by fneitzel** [comment] 2015-09-09 11:50
Thank you for the quick response.

I understand the issue concerning the file names.
Let's say i take care for any circumstances that there are equal file names on client and server.

I prefer to have a possibility to delete the log files within the app and without any file manager.
Some function like: delete all log files - delete after 2 days

Is that also not possible?

**Comment by yrtimiD** [comment] 2015-09-16 10:48
If I understand right, after you hit "stop logging" and app configured to create a new file on each start - we'll not loose any data if will remove file after upload finish?
Auto upload is really great, but because I can't be sure that all files in directory are uploaded - it's hard to decide if I can delete them or not.

**Comment by mendhak** [comment] 2015-09-16 17:47
I've been thinking about this quite a bit recently.  My main issue with deleting files is twofold:

1.  It turns GPSLogger into a file manager, because there will be desire for finer or more complex control over what gets deleted.
2.  Accidentally deleting a file can lead to data loss, disastrous.

The approach has always been to avoid management of the files, specifically tracking what's in it, tracking a delete, tracking last upload time, or even assuming it exists. 

For that reason I want to know more about this.  Example, why not use a file manager? And is the reason for wanting to delete files related to space saving?

In terms of implementation I did think of a delete action after an upload action just like @yrtimiD mentioned, but if there are multiple upload destinations then it could never happen since some upload attempts give up after *x* attempts.  

I also thought, what about a button that the user has to manually press when they want files deleted, it opens up a file list and they select ones they want to delete via a checkbox. But then the user may want to see time stamps against it, etc.

**Comment by ascherer** [comment] 2019-06-02 15:11
Possibly unrelated, but frustrating: My very first logfile has disappeared, after I exited the app.

**Comment by mendhak** [comment] 2019-06-05 18:35
What do you mean disappeared, there is no delete functionality in the app even now, so the file won't be deleted.  It's entirely possible nothing ever recorded, were any of the file logging types enabled and was the file present?

**Comment by ascherer** [comment] 2019-06-05 20:03
The file was present and non-empty while the app was running. After I quit the app, the log directory was empty.

**Comment by mendhak** [comment] 2019-06-09 09:39
What file explorer did you use to verify that the file was present + the file had contents?  Also what was the path of the file you checked?

If you're able to recreate the issue on a regular basis, then having a look at the [debug log](https://gpslogger.app/#troubleshooting) would be useful here.

**Comment by ascherer** [comment] 2019-06-09 10:18
I'm using the Power File Manager and its text file editor showed the usual xml contents of a gpx file. The file was located at `/storage/emulated/0/Android/data/domain-of-your-app/files/20190601.gpx`.

Time permitting, I'll give GPSLogger Android another try.

**Comment by ascherer** [comment] 2019-08-24 15:41
@mendhak Back from second trial run. I'll have to experiment a litlle with the time and distance intervals for my handbike tours, but otherwise I have found the cause of my disappearing logfile:

It is the **texteditor** of Power File Manager – reproducible!

Clicking on the `gpslogger.gpx` file suggests to open it in the texteditor and this shows the GPX contents correctly. Swiping left back in the directory view then _eliminates_ the file. One _has_ to click "Save" to keep the file intact. Weird!

**Comment by mendhak** [comment] 2019-08-29 18:40
Whoa, I just tried what you said and the contents of the file were deleted without warning!  I'm not sure how that could happen as handling a back button press in Android is its own method and you'd have to deliberately remove the contents of the file for this to happen.  It's definitely worth an email to the developer.  

I don't know if you're particularly intent on that editor, I use [QuickEdit](https://play.google.com/store/apps/details?id=com.rhmsoft.edit) - it's decent enough for basic needs.  But if you know any better ones I'd also like to know

**Comment by ascherer** [comment] 2019-08-29 20:27
Normally I don't look into gpx files with a text editor, I rather use **gpsprune** for visualization. I _had_ to hack the dates in gpx files extracted from my **i-Blue 747 Pro S** logger after the GPS week rollover. After 1999-12-31 it jumped into the year 2039, which balked **bt747**, and I tried your app again. After a few test tours over the passed days I'm really satisfied with the results and the file naming. I simply copy the **gpslogger** files from the phone to my desktop computer under **git** control.

On the first test runs I was bitten hard by this evil bug. I hadn't had time to call the **pfm** programmer about this nasty mis-feature. Other than in this situation I don't use the **pfm** text editor.

My favorite way to edit texts on Android, apart from Github comments, is **AndTidWiki**. I do all my typing on Android with the **Hacker's Keyboard** in the German layout.

**Comment by mendhak** [comment] 2019-08-31 21:57
Thanks for sharing that, it's an interesting list.  I am really liking Hacker's Keyboard.  I wish I had known about this earlier, exactly what I need for SSH and terminal work.  Thanks!

**Comment by Mirarkitty** [comment] 2020-02-27 11:52
I think I need this option. I'm using gpslogger to stand alone send position of a device over the net; noone will use the device directly...

**Comment by fuxoft** [comment] 2020-11-15 17:35
> Not possible, reason: Uploads happen in parallel with the file writing, that means they can happen within second or within hours of a log being written (based on internet connectivity, schedule, naming). In turn that means that deleting a file after it is uploaded will cause data loss. Also, in the case of Dropbox/GDrive it would cause data loss online as the same file is being overwritten with different contents.

Could there be a simple delete implementation in the vein of "Once a day, at some arbitrary time, automatically delete all log files that were not modified in the last X days", with "X" being configurable? Just to make sure that my log directory is not full of dozens / thousands of old, unneeded files. For example, I could upload files from GPSlogger each day and have them automatically deleted 14 days after the last modification. If something tragic happens and I don't upload my files for 14 days, then I lose some of them - that's my problem and I won't blame GPSlogger. I guess the option should come with big bold warning...

**Comment by mendhak** [comment] 2020-11-20 09:47
A way I can think of right now is if you did the deletes using Tasker/Llama/MacroDroid/AutomateIt, which would require running some shell commands to check on the last modified date, before deleting them.  

An addition to that could be if you used something like [Folder Sync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite&utm_source=apkdot.com) to do the uploads yourself. 

With these two combined you needn't rely on GPSLogger to do the file management.

**Comment by Mirarkitty** [comment] 2020-12-30 07:53
I don't want gps logger to generate files in the first place... :D

**Comment by fuxoft** [comment] 2020-12-30 09:38
> I personally don't want gps logger to generate files in the first place... :D

You can definitely do that. For example I am using GPSLogger to log position to an external URL, without generating any files on my phone.

**Comment by mendhak** [comment] 2023-04-07 17:40
Closing this issue, the nearest I've been able to implement, although not automated, is a manual file delete in logging settings.

**Closed by mendhak** 2023-04-07 17:40 UTC
Labels: discuss
