### ISSUE TITLE
Custom URL does not work from version 120, with 119 it works.

### ISSUE THREAD

**Issue by wimiti** [mendhak/gpslogger#987] opened 2022-06-29 07:30 UTC
Since you upgrade to version 120 and later, the "Custom URL" option does not work with the same settings as for the previous version 119.

For example, in version 122, looking at the log, after 5 attempts it tells me "Custom URL -Could not upload the file" and "Custom URL: maximum attempts failed, giving up".

Also indicate that the SSL certificate has been validated correctly in the configuration.

That could be happening?

Thanks for the development of the application and the attention on this issue.

W.

**Comment by mendhak** [comment] 2022-06-29 19:10
Hi what you'll want to do is record a debug log:  https://gpslogger.app/#troubleshooting

Then recreate the problem.  Then, look at the log to see what the problem is, it might be really apparent, or you can post it here, (but probably hide any location info and hide the domain name of what you're connecting to), or you can email it to me - `gpslogger` at `mendhak.com` and I can have a look.

**Comment by mendhak** [comment] 2022-08-01 20:13
Sorry late reply.  So, I saw the logs.  The main error with redacted information is

    javax.net.ssl.SSLPeerUnverifiedException: Hostname domain.name.yes not verified:
    certificate: sha256/1APJK3/Uc0ywS3Ix+lTU9FSwFpaVaVV05oAtIkX1wZQ=
    DN: 1.2.840.113549.1.9.1=--------------------------id------------------------------------------,CN=domain.name.yes,OU=Private,O=DomainName,L=TATA,ST=TATA,C=WORLD
    subjectAltNames: []
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:316) ~[na:0.0]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:270) ~[na:0.0]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162) ~[na:0.0]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[na:0.0]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[na:0.0]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[na:0.0]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[na:0.0]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[na:0.0]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[na:0.0]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[na:0.0]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[na:0.0]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[na:0.0]
	at com.mendhak.gpslogger.loggers.customurl.CustomUrlJob.onRun(CustomUrlJob.java:78) ~[na:0.0]
	at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) ~[na:0.0]
	at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) ~[na:0.0]
	at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:923) ~[na:0.0]

    20:02:18 INFO  CustomUrlJob.onRun:62 - HTTP Request - https://domain.name.yes/nextcloud/xxxxxxxxxxxxxxxx
    20:02:18 DEBUG Networks.getKnownServersStore:56 - Getting local truststore - /storage/emulated/0/Android/data/com.mendhak.gpslogger/files/knownservers.bks
    20:02:18 DEBUG LocalX509TrustManager.isKnownServer:144 - Checking for certificate - HashCode: -1322352508, Subject: 1.2.840.113549.1.9.1=--------------------------id------------------------------------------,CN=domain.name.yes,OU=Private,O=DomainName,L=TATA,ST=TATA,C=WORLD, in keystore: true


From what I can tell, the certificate validation test did work, because the `in keystore: true` appears.  

I had a look at the code changes between version 119 and 120.  The main change is the library version of okhttp, from 3.7 to 3.10.  And in their [changelog](https://square.github.io/okhttp//changelogs/changelog_3x/#version-370), this message seems to match up with the above behavior.  

> New: Don’t fall back to common name (CN) verification for hostnames. This behavior was deprecated with RFC 2818 in May 2000 and was recently dropped from major web browsers.

So could you try regenerating the certificate, but adding the domain name to the SAN list (subjectAltNames) of the certificate and try again?

**Comment by wimiti** [comment] 2022-09-02 19:29
Thank you for reviewing the debuglog that I sent you.
After a few weeks disconnected, I have been able to return to the topic and I have done what you have indicated. I have created a new certificate with SAN list (subjectAltNames) and it already works in versions higher than #119 (specifically, I have tried it in the most recent #123).
Thanks for everything.

**Comment by mendhak** [comment] 2022-09-03 13:51
Nice, that's good to hear.  OK will close the issue.

**Closed by mendhak** 2022-09-03 13:51 UTC
