### ISSUE TITLE
Option 'Don't log if I'm not moving'

### ISSUE THREAD

**Issue by frepelkweeltje** [mendhak/gpslogger#799] opened 2020-01-22 12:09 UTC
Hi,

I'm enjoying gpslogger quite a lot. I aim to log every 5 min but not when my phone is not moving. However, the option 'Don't log if I'm not moving' seems to work different than expected. 

When disabled, gpslogger indeed tries to log every 5 min.

When enabled and I don't move, gpslogger does not log as expected.

However, when enabled and I do move, I was expecting that gpslogger would try to log every 5 min. Instead, It requests a location almost every minute, which causes the battery to drain faster.

So apart from not logging when not moving, the option 'Don't log if I'm not moving' seems to increase the logging frequency when moving. Is this by design or is something else going on?

Thanks!

**Comment by mendhak** [comment] 2020-02-06 18:14
There'll be something else going on - the don't log logic still checks for time intervals, so you should still be seeing 5 minutes.  Could you [record a log file](https://gpslogger.app/#troubleshooting) and send it?  And do you have passive logging enabled?  If so - that would log a location regardless of filters as the energy to acquire a point has happened in another application.  See if there are other applications requesting location more frequently than 5 minutes

**Comment by jgoerzen** [comment] 2020-03-03 14:46
I'm seeing something similar on my Pixel 2 XL, Android 10.

I have the interval set to 300 seconds.  However, while driving down a bumpy road, it sent updates about every 5 seconds.

Interestingly enough, when "Don't log if I'm not moving" is DISABLED, after about 10 minutes of sitting on a table, it stops sending updates every 5 mintues.  But with it enabled, it DOES send updates every 5 minutes.  I am puzzled by all of this.

I will try to capture a log.

**Comment by jgoerzen** [comment] 2020-03-03 14:52
Is it possible this is a duplicate of #586 ?

**Comment by mendhak** [comment] 2023-01-06 23:05
Closing this, since the option was removed with the move to FDroid (it used the Activity Recognition API, but that API is closed source, so it's not allowed in F-Droid, so it got removed).

**Closed by mendhak** 2023-01-06 23:05 UTC
